// Possíveis condições climáticas PT-BR

const weatherConditions = {
  Sunny: 'Ensolarado',
  Clear: 'Limpo',
  'Partly Cloudy ': 'Parcialmente nublado',
  Cloudy: 'Nublado',
  Overcast: 'Encoberto',
  'Patchy rain nearby': 'Chuva irregular nas proximidades',
  'Thundery outbreaks possible': 'Possíveis surtos de trovoada',
  'Blowing snow': 'Neve soprando',
  Blizzard: 'Nevasca',
  Fog: 'Nevoeiro',
  'Freezing fog': 'Nevoeiro congelante',
  'Patchy light drizzle': 'Garoa leve irregular',
  'Light drizzle': 'Garoa leve',
  'Freezing drizzle': 'Garoa congelante',
  'Heavy freezing drizzle': 'Garoa congelante forte',
  'Patchy light rain': 'Chuva leve irregular',
  'Light rain': 'Chuva leve',
  'Moderate rain at times': 'Chuva moderada às vezes',
  'Moderate rain': 'Chuva moderada',
  'Heavy rain at times': 'Chuva forte às vezes',
  'Heavy rain': 'Chuva forte',
  'Light freezing rain': 'Chuva congelante leve',
  'Moderate or heavy freezing rain': 'Chuva congelante moderada ou forte',
  'Light sleet': 'Granizo leve',
  'Moderate or heavy sleet': 'Granizo moderado ou forte',
  'Patchy light snow': 'Neve leve irregular',
  'Light snow': 'Neve leve',
  'Patchy moderate snow': 'Neve moderada irregular',
  'Moderate snow': 'Neve moderada',
  'Patchy heavy snow': 'Neve forte irregular',
  'Heavy snow': 'Neve forte',
  'Ice pellets': 'Pelotas de gelo',
  'Light rain shower': 'Pancada de chuva leve',
  'Moderate or heavy rain shower': 'Pancada de chuva moderada ou forte',
  'Torrential rain shower': 'Pancada de chuva torrencial',
  'Light sleet showers': 'Pancadas de granizo leve',
  'Moderate or heavy sleet showers': 'Pancadas de granizo moderadas ou fortes',
  'Light snow showers': 'Pancadas de neve leve',
  'Moderate or heavy snow showers': 'Pancadas de neve moderadas ou fortes',
  'Light showers of ice pellets': 'Pancadas leves de pelotas de gelo',
  'Moderate or heavy showers of ice pellets': 'Pancadas moderadas ou fortes de pelotas de gelo',
  'Patchy light rain with thunder': 'Chuva leve irregular com trovoadas',
  'Moderate or heavy rain with thunder': 'Chuva moderada ou forte com trovoadas',
  'Patchy light snow with thunder': 'Neve leve irregular com trovoadas',
  'Moderate or heavy snow with thunder': 'Neve moderada ou forte com trovoadas',
};

export const translateCondition = (condition) => {
  return weatherConditions[condition] || condition;
};
